# Generated by Django 5.0.6 on 2024-06-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Бух_учет",
            fields=[
                ("id_check", models.AutoField(primary_key=True, serialize=False)),
                ("debt", models.FloatField()),
                ("sales", models.FloatField()),
                ("count_goods", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Коллекция",
            fields=[
                ("id_collection", models.AutoField(primary_key=True, serialize=False)),
                ("season", models.IntegerField()),
                ("year", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Поставщик",
            fields=[
                ("id_seller", models.AutoField(primary_key=True, serialize=False)),
                ("trade_mark", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Каталог",
            fields=[
                ("id_catalog", models.AutoField(primary_key=True, serialize=False)),
                ("shirts", models.IntegerField()),
                ("t_shirts", models.IntegerField()),
                ("hoodies", models.IntegerField()),
                (
                    "id_seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_app.поставщик",
                    ),
                ),
            ],
        ),
    ]
